# Generated by Django 5.0 on 2024-03-05 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoAppUser', '0003_remove_task_assigned_user_subtask_assigned_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_img',
            field=models.ImageField(blank=True, upload_to='user_img'),
        ),
    ]
