# Generated by Django 5.0 on 2024-03-05 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoAppUser', '0004_invitation_created_at_alter_customuser_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoAppUser.invitation'),
        ),
    ]
